// export const baseUrl = 'http://192.168.1.7:3000'
export const baseUrl = 'https://cho-cu-tttn.herokuapp.com'

export const API_REQUEST_LOCATION = baseUrl + '/location'
export const API_REQUEST_LOCATION_PROVINCES = baseUrl + '/location/provinces'
export const API_REQUEST_LOCATION_DISTRICTS = baseUrl + '/location/districts'
export const API_REQUEST_LOCATION_WARDS = baseUrl + '/location/wards'
export const API_REQUEST_AUTH_ADMIN = baseUrl + '/admin/login'
export const API_REQUEST_ADMIN_ALL_POSTS = baseUrl + '/admin/all-post'
export const API_REQUEST_ADMIN_ALL_USERS = baseUrl + '/admin/all-user'
export const API_REQUEST_PENDING_POST = baseUrl + '/admin/pending-post'
export const API_REQUEST_APPROVE_POST = baseUrl + '/admin/approve-post'
export const API_REQUEST_DELETE_POST = baseUrl + '/admin/lock-post'
export const API_REQUEST_DENY_POST = baseUrl + '/admin/deny-post'
export const API_REQUEST_LOCK_ACCOUNT = baseUrl + '/admin/lock-account'
export const API_REQUEST_UNLOCK_ACCOUNT = baseUrl + '/admin/unlock-account'
export const API_LOGOUT_ADMIN = baseUrl + '/admin/logout'
export const API_REQUEST_REPORTS = baseUrl + '/admin/reports'
export const API_REQUEST_CLEAR_POST_REPORTS = baseUrl + '/admin/clear-report'

export const API_REQUEST_USER_DATA = baseUrl + '/user'
export const API_REQUEST_UPDATE_USER_INFO = baseUrl + '/user/update-info'
export const API_REQUEST_USER_PAYMENTS = baseUrl + '/user/user-payments'
export const API_REQUEST_ADD_USER_PAYMENTS = baseUrl + '/user/add-user-payment'
export const API_REQUEST_ADD_USER_SERVICE = baseUrl + '/user/add-user-service'
export const API_REQUEST_REMOVE_USER_PAYMENTS =
  baseUrl + '/user/remove-user-payment'
export const API_REQUEST_USER_POSTS = baseUrl + '/user/user-posts'
export const API_REQUEST_AUTH_TOKEN = baseUrl + '/user/login'
export const API_LOGOUT = baseUrl + '/user/logout'
export const API_CREATE_ACCOUNT = baseUrl + '/user/create-account'
export const API_FORGOT_PASSWORD = baseUrl + '/user/forgot-password'
export const API_SUBSCRIBE_NOTIFY = baseUrl + '/user/subcribe-notify'
export const API_UNSUBSCRIBE_NOTIFY = baseUrl + '/user/unsubcribe-notify'
export const API_REQUEST_CATEGORIES = baseUrl + '/category'
export const API_REQUEST_UPDATE_CATEGORIES = baseUrl + '/category/update'
export const API_REQUEST_DELETE_CATEGORIES = baseUrl + '/category/delete'
export const API_REQUEST_CATEGORY_DETAILS = baseUrl + '/category/list-details/'
export const API_REQUEST_CATEGORY_ADD_DETAILS =
  baseUrl + '/category/add-details'
export const API_REQUEST_CATEGORY_REMOVE_DETAILS =
  baseUrl + '/category/remove-details'
export const API_REQUEST_DETAILS = baseUrl + '/details'
export const API_REQUEST_UPDATE_DETAILS = baseUrl + '/details/update'
export const API_REQUEST_DELETE_DETAILS = baseUrl + '/details/delete'
export const API_REQUEST_POSTS = baseUrl + '/post'
export const API_REQUEST_CREATE_POST = baseUrl + '/post/create-post'
export const API_REQUEST_EDIT_POST = baseUrl + '/post/edit-post'
export const API_REQUEST_END_POST = baseUrl + '/post/end-post'
export const API_REQUEST_REPOST_POST = baseUrl + '/post/repost-post'
export const API_REQUEST_PAYMENTS = baseUrl + '/payment'
export const API_REQUEST_CREATE_DEAL = baseUrl + '/deal/create-deal'
export const API_REQUEST_SELL_DEALS = baseUrl + '/deal/sell-history'
export const API_REQUEST_BUY_DEALS = baseUrl + '/deal/buy-history'
export const API_REQUEST_GET_DEAL = baseUrl + '/deal'
export const API_REQUEST_UPDATE_DEAL_STATE = baseUrl + '/deal/update-deal-state'
export const API_REQUEST_RATE_DEAL = baseUrl + '/deal/rate-deal'
export const API_REQUEST_GET_DEAL_RATING = baseUrl + '/deal/rating'
export const API_REQUEST_GET_OTP = baseUrl + '/otp/create'
export const API_REQUEST_VERIFY_OTP = baseUrl + '/otp/verify'

export const API_REQUEST_POST_TURN_SERVICES = baseUrl + '/services'
export const API_REQUEST_ADD_POST_TURN_SERVICES = baseUrl + '/services/add'
export const API_REQUEST_UPDATE_POST_TURN_SERVICES =
  baseUrl + '/services/update'
export const API_REQUEST_DELETE_POST_TURN_SERVICES =
  baseUrl + '/services/delete'
