export const ACCESS_TOKEN = 'ACCESS_TOKEN'
export const CURRENT_LANGUAGE = 'CURRENT_LANGUAGE'
export const CURRENT_USER = 'CURRENT_USER'
export const CURRENT_THEME = 'CURRENT_THEME'

export const NOTIFY_TOKEN_FCM = 'NOTIFY_TOKEN_FCM'
export const NOTIFICATIONS = 'NOTIFICATIONS'
